### ISSUE TITLE
Rendering issues?

### ISSUE THREAD

**Issue by farbodsz** [FarbodSalamat-Zadeh/UsefulViews#21]
I am getting the following error, when using the `LabelledSpinner` in my layout (v1.1.4):

> The following classes could not be instantiated:
> - com.farbod.labelledspinner.LabelledSpinner (Open Class, Show Exception, Clear Cache)
>  Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE

```
java.lang.NullPointerException
    at com.farbod.labelledspinner.LabelledSpinner.alignLabelWithSpinnerItem(LabelledSpinner.java:600)
    at com.farbod.labelledspinner.LabelledSpinner.<init>(LabelledSpinner.java:146)
    at com.farbod.labelledspinner.LabelledSpinner.<init>(LabelledSpinner.java:112)
    at com.farbod.labelledspinner.LabelledSpinner.<init>(LabelledSpinner.java:108)
    at sun.reflect.GeneratedConstructorAccessor600.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    ...
```

Is any one else getting the same issue?

**Comment by farbodsz** [comment]
After some experimenting, I've found that I do _not_ get this issue in version 1.1.3, so it seems to be a version 1.1.4 issue.

**Comment by farbodsz** [comment]
If anyone finds a solution, feel free to post here...

**Comment by farbodsz** [comment]
Version 1.1.5 does not change anything regarding this issue.
